### ISSUE TITLE
读取本地缓存的账号密码信息赋值给TextEditingController会报错

### ISSUE THREAD

**Issue by heliff** [alibaba/fish-redux#268]
```dart
context.dispatch(LoginActionCreator.accountAction(await SharedPreferenceUtil.getString('name'),await SharedPreferenceUtil.getString('pass')));

LoginState _account(LoginState state, Action action) {
  final Map<String, String> update = action.payload ?? <String, String>{};
  final LoginState newState = state.clone();
  newState.nameEditingController.text = update['name'] ?? state.name;
  newState.passEditingController.text = update['pass'] ?? state.pass;
  newState.name = update['name'] ?? state.name;
  newState.pass = update['pass'] ?? state.pass;
  return newState;
}

I/flutter ( 6466): ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
I/flutter ( 6466): The following ArgumentError was thrown while dispatching notifications for TextEditingController:
I/flutter ( 6466): Invalid argument(s): Reducers may not dispatch actions.
I/flutter ( 6466): When the exception was thrown, this was the stack:
I/flutter ( 6466): #0      _throwIfNot (package:fish_redux/src/redux/create_store.dart:11:5)
I/flutter ( 6466): #1      _createStore.<anonymous closure> (package:fish_redux/src/redux/create_store.dart:35:7)
I/flutter ( 6466): #2      Logic._applyOnAction.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:fish_redux/src/redux_component/logic.dart:139:15)
I/flutter ( 6466): #3      DefaultContext.dispatch (package:fish_redux/src/redux_component/context.dart:59:38)

```

**Comment by hzgotb** [comment]
Invalid argument(s): Reducers may not dispatch actions。无效参数。你排查一下。

**Comment by zjuwjf** [comment]
原因：
nameEditingController 或者 passEditingController 里有当text发生变化时，会触发reducer。
所以当 
newState.nameEditingController.text = update['name'] ?? state.name;
newState.passEditingController.text = update['pass'] ?? state.pass;

使得在reducer进行过程内部，在此触发reducer，导致异常。

真确的做法：
```dart
LoginState _account(LoginState state, Action action) {
  final Map<String, dynamic> update = action.payload ?? <String, String>{};
  final LoginState newState = state.clone();
  newState.nameEditingController = update['nameEditingController'] ;
  newState.passEditingController= update['passEditingController'];
  newState.name = update['name'] ?? state.name;
  newState.pass = update['pass'] ?? state.pass;
  return newState;
}
```

其中update['nameEditingController']是新创建的controller

**Comment by heliff** [comment]
context.dispatch(LoginActionCreator.accountAction(await SharedPreferenceUtil.getString('name'),await SharedPreferenceUtil.getString('pass')));
  context.state.nameEditingController.addListener((){
    context.dispatch(LoginActionCreator.updateAction(context.state.nameEditingController.text,null));
  });
  context.state.passEditingController.addListener((){
    context.dispatch(LoginActionCreator.updateAction(null, context.state.passEditingController.text));
  });  
感谢大佬指点，把监听加在后面，就不报错了。
