### ISSUE TITLE
Lifecycle.dispose

### ISSUE THREAD

**Issue by crystal-lee** [alibaba/fish-redux#345]
fish -redux 中这个super.dispose()是在哪里调用的呢？
怎么样可以在controller.dispose()之后调用super.dispose()
```
@override
  void dispose() {
    // 资源释放
    controller.dispose();
    super.dispose();
  }
```
在effect中，Lifecycle.dispose去调用释放AnimationController报错
```
Effect<ChatContentState> buildEffect() {
  return combineEffects(<Object, Effect<ChatContentState>>{
    ChatContentAction.action: _onAction,
    Lifecycle.initState: _onInitAction,
    Lifecycle.dispose: _onDisposeAction,
  });
}

void _onDisposeAction(Action action, Context<ChatContentState> ctx) {
    ctx.state.animationController.dispose();//报错
    ctx.stfState.dispose();
}

void _onInitAction(Action action, Context<ChatContentState> ctx) {
  final Object tickerProvider = ctx.stfState;
  AnimationController controller = AnimationController(vsync: tickerProvider, duration: const Duration(milliseconds: 2000));
  ctx.dispatch(ChatContentActionCreator.onCreateControllerAction(controller));
}
```
```
```

**Comment by zjuwjf** [comment]
预期不应该调用下面的代码。
```dart
ctx.stfState.dispose();
```

**Comment by crystal-lee** [comment]
> 预期不应该调用下面的代码。
> 
> ```dart
> ctx.stfState.dispose();
> ```
为了使用动画
```
class ChatContentComponent extends Component<ChatContentState> with TickerProviderMixin<ChatContentState>{
  ChatContentComponent()
      : super(
            effect: buildEffect(),
            reducer: buildReducer(),
            view: buildView,
            dependencies: Dependencies<ChatContentState>(
                adapter: null,
                slots: <String, Dependent<ChatContentState>>{
                }),);

}
```

```ctx.stfState.dispose();```应该相当于上面的```super.dispose();```，是调用的```TickerProviderStateMixin```的```dispose()```把

不调用的话，也会报错
```
I/flutter (10165): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (10165): The following assertion was thrown while finalizing the widget tree:
I/flutter (10165): _TickerProviderStfState<ChatContentState>#c9c35(tickers: tracking 1 ticker) was disposed with an
I/flutter (10165): active Ticker.
I/flutter (10165): _TickerProviderStfState<ChatContentState> created a Ticker via its TickerProviderStateMixin, but at
I/flutter (10165): the time dispose() was called on the mixin, that Ticker was still active. All Tickers must be
I/flutter (10165): disposed before calling super.dispose(). Tickers used by AnimationControllers should be disposed by
I/flutter (10165): calling dispose() on the AnimationController itself. Otherwise, the ticker will leak.
I/flutter (10165): The offending ticker was: _WidgetTicker(created by
I/flutter (10165): _TickerProviderStfState<ChatContentState>#c9c35(lifecycle state: created, tickers: tracking 0
I/flutter (10165): tickers))
I/flutter (10165): The stack trace when the _WidgetTicker was actually created was:
I/flutter (10165): #0      new Ticker.<anonymous closure> (package:flutter/src/scheduler/ticker.dart:64:40)
I/flutter (10165): #1      new Ticker (package:flutter/src/scheduler/ticker.dart:66:6)
I/flutter (10165): #2      new _WidgetTicker (package:flutter/src/widgets/ticker_provider.dart:225:80)
I/flutter (10165): #3      __TickerProviderStfState&ComponentState&TickerProviderStateMixin.createTicker (package:flutter/src/widgets/ticker_provider.dart:161:34)
I/flutter (10165): #4      new AnimationController (package:flutter/src/animation/animation_controller.dart:244:21)
I/flutter (10165): #5      _onInitAction (package:fish_redux_example/send_page/chat_content_list_component/chat_content_component/effect.dart:24:36)
I/flutter (10165): #6      combineEffects.<anonymous closure> (package:fish_redux/src/redux_component/helper.dart:67:31)
I/flutter (10165): #7      asHigherEffect.<anonymous closure>.<anonymous closure> (package:fish_redux/src/redux_component/helper.dart:71:52)
I/flutter (10165): #8      Logic._applyOnAction.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:fish_redux/src/redux_component/logic.dart:127:43)
I/flutter (10165): #9      DefaultContext.onLifecycle (package:fish_redux/src/redux_component/context.dart:85:5)
I/flutter (10165): #10     ComponentState.initState (package:fish_redux/src/redux_component/component.dart:246:14)
I/flutter (10165): #11     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3846:58)
I/flutter (10165): #12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (10165): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (10165): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (10165): #15     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (10165): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (10165): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (10165): #18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (10165): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (10165): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (10165): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (10165): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (10165): #23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (10165): #24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (10165): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (10165): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (10165): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (10165): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (10165): #29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (10165): #30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (10165): #31     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4063:11)
I/flutter (10165): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (10165): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (10165): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (10165): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (10165): #36     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (10165): #37     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (10165): #38     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (10165): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (10165): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (10165): #41     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1034:36)
I/flutter (10165): #42     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1019:20)
I/flutter (10165): #43     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2258:19)
I/flutter (10165): #44     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1012:11)
I/flutter (10165): #45     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:275:23)
I/flutter (10165): #46     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1740:58)
I/flutter (10165): #47     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:797:15)
I/flutter (10165): #48     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1740:13)
I/flutter (10165): #49     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:264:5)
I/flutter (10165): #50     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:410:5)
I/flutter (10165): #51     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:191:19)
I/flutter (10165): #52     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:234:19)
I/flutter (10165): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (10165): #54     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
I/flutter (10165): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (10165): #56     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:407:13)
I/flutter (10165): #57     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1322:12)
I/flutter (10165): #58     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1240:20)
I/flutter (10165): #59     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1519:7)
I/flutter (10165): #60     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
I/flutter (10165): #61     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:347:19)
I/flutter (10165): #62     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter (10165): #63     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter (10165): #64     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter (10165): #65     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter (10165): #66     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
I/flutter (10165): #70     _invoke (dart:ui/hooks.dart:219:10)
I/flutter (10165): #71     _drawFrame (dart:ui/hooks.dart:178:3)
I/flutter (10165): (elided 3 frames from package dart:async)
I/flutter (10165): 
I/flutter (10165): When the exception was thrown, this was the stack:
I/flutter (10165): #0      __TickerProviderStfState&ComponentState&TickerProviderStateMixin.dispose.<anonymous closure> (package:flutter/src/widgets/ticker_provider.dart:178:13)
I/flutter (10165): #1      __TickerProviderStfState&ComponentState&TickerProviderStateMixin.dispose (package:flutter/src/widgets/ticker_provider.dart:191:6)
I/flutter (10165): #2      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:3916:12)
I/flutter (10165): #3      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1697:13)
I/flutter (10165): #4      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (10165): #5      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
I/flutter (10165): #6      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (10165): #7      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (10165): #8      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
I/flutter (10165): #9      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (10165): #10     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (10165): #11     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter (10165): #12     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (10165): #13     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (10165): #14     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter (10165): #15     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (10165): #16     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (10165): #17     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter (10165): #18     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (10165): #19     ListIterable.forEach (dart:_internal/iterable.dart:39:13)
I/flutter (10165): #20     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1706:25)
I/flutter (10165): #21     BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2364:27)
I/flutter (10165): #22     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2196:15)
I/flutter (10165): #23     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2363:7)
I/flutter (10165): #24     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:702:18)
I/flutter (10165): #25     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter (10165): #26     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter (10165): #27     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter (10165): #28     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
I/flutter (10165): #32     _invoke (dart:ui/hooks.dart:219:10)
I/flutter (10165): #33     _drawFrame (dart:ui/hooks.dart:178:3)
I/flutter (10165): (elided 3 frames from package dart:async)
I/flutter (10165): ════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by zjuwjf** [comment]
能给一个可以复现的demo么？


```dart
ctx.stfState.dispose();
```

这行会由框架自动调用。

**Comment by zjuwjf** [comment]
#386

**Comment by zjuwjf** [comment]
如果有更多信息，欢迎继续打开和讨论。

**Comment by EaglesChen** [comment]
@zjuwjf 大佬这个是解决了么 我也是创建了一个循环动画 dispose的时候出现上面错误.

**Comment by LeeCareFree** [comment]
@crystal-lee 大佬这个问题是解决了吗？可否告知。
