### ISSUE TITLE
EffectMiddleware

### ISSUE THREAD

**Issue by chaishuanzhu** [alibaba/fish-redux#383]
**EffectMiddleware放在有DynamicFlowAdapter的页面中报错，是写法有问题吗**
在没有Adapter的页面是正常的。
```dart
class ToDoListPage extends Page<PageState, Map<String, dynamic>> {
  ToDoListPage()
      : super(
          initState: initState,
          effect: buildEffect(),
          reducer: buildReducer(),
          view: buildView,
          dependencies: Dependencies<PageState>(
              adapter: NoneConn<PageState>() + ToDoListAdapter(),
              slots: <String, Dependent<PageState>>{
                'report': ReportConnector() + ReportComponent()
              }),
          middleware: <Middleware<PageState>>[
            logMiddleware(tag: 'ToDoListPage'),
          ],
          effectMiddleware: <EffectMiddleware<PageState>>[
            pageAnalyticsMiddleware(tag: 'ToDoListPage'),
          ],
        );
}
```
page_analytics.dart
```dart
import 'package:fish_redux/fish_redux.dart';

EffectMiddleware<T> pageAnalyticsMiddleware<T>({String tag = 'redux'}) {
  return (AbstractLogic<dynamic> logic, Store<T> store) {
    return (Effect<T> effect) {
      return (Action action, Context<dynamic> ctx) {
        return effect(action, ctx);
      };
    };
  };
}
``` 

**To Reproduce**
```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown building PageProvider:
flutter: The method 'call' was called on null.
flutter: Receiver: null
flutter: Tried calling: call(Instance of 'Action', Instance of 'RecycleContext<PageState>')
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
flutter: #1      pageAnalyticsMiddleware.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:sample/page_analytics.dart:41:22)
flutter: #2      Logic.createOnEffect.<anonymous closure> (package:fish_redux/src/redux_component/logic.dart:71:51)
flutter: #3      Logic.createOnEffect.<anonymous closure> (package:fish_redux/src/redux_component/logic.dart:74:45)
flutter: #4      DispatchBusDefault.dispatch (package:fish_redux/src/redux_component/dispatch_bus.dart:32:15)
flutter: #5      LogicContext.broadcastEffect (package:fish_redux/src/redux_component/context.dart:119:11)
flutter: #6      Logic.createAfterEffect.<anonymous closure> (package:fish_redux/src/redux_component/logic.dart:89:13)
flutter: #7      Logic.createDispatch.<anonymous closure> (package:fish_redux/src/redux_component/logic.dart:101:13)
flutter: #8      LogicContext.dispatch (package:fish_redux/src/redux_component/context.dart:74:38)
flutter: #9      _init (package:sample/todo_list_page/effect.dart:38:7)
flutter: #10     combineEffects.<anonymous closure> (package:fish_redux/src/redux_component/helper.dart:69:31)
flutter: #11     EnhancerDefault._inverterEffect.<anonymous closure> (package:fish_redux/src/redux_component/enhancer.dart:117:56)
flutter: #12     pageAnalyticsMiddleware.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:sample/page_analytics.dart:41:22)
flutter: #13     Logic.createOnEffect.<anonymous closure> (package:fish_redux/src/redux_component/logic.dart:71:51)
flutter: #14     Logic.createOnEffect.<anonymous closure> (package:fish_redux/src/redux_component/logic.dart:74:45)
flutter: #15     Logic.createDispatch.<anonymous closure> (package:fish_redux/src/redux_component/logic.dart:96:41)
flutter: #16     LogicContext.onLifecycle (package:fish_redux/src/redux_component/context.dart:89:5)
```

**Comment by zjuwjf** [comment]
应该是这样
```dart
import 'package:fish_redux/fish_redux.dart';

EffectMiddleware<T> pageAnalyticsMiddleware<T>({String tag = 'redux'}) {
  return (AbstractLogic<dynamic> logic, Store<T> store) {
    return (Effect<T> effect) {
      return (Action action, Context<dynamic> ctx) {
        return effect?.call(action, ctx);
      };
    };
  };
}
```

设计上并不保证每一个Component或者Adapter都有他的Effect部分。这完全由开发者自己来确定。

但是从切面的角度，是期望即使一个Component或Adapter没有注册它的Effect，也能切入到它基本的生命周期的响应情况。

**Comment by zjuwjf** [comment]
感谢提醒，这个应该增加下代码注释说明。

**Comment by zjuwjf** [comment]
#390
